name: Trigger auto deployment for cipher-relay-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cipher-relay-container-AutoDeployTrigger-6989d21d-e82c-4e58-915d-c2c411600438.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CIPHERRELAYCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CIPHERRELAYCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CIPHERRELAYCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        run: |
          az acr build --image cipher-relay-container:latest --registry cipherregistry1 --file Adarsh/p2p_transport/DockerfileRelay Adarsh/p2p_transport/


